#!/bin/sh /etc/rc.common

USE_PROCD=1
PROG=/usr/bin/rtdnet-mqtt-gateway
CFGNAME=rtdnet_gateway

START=99

rtdnet_gateway_instance()
{
  local config="$1"
  local broker_host;
  local broker_user;
  local broker_pw;
  local id;
  local device;
  local server_address;
  local publish_delay;

  config_get broker_host ${config} broker_host
  config_get broker_user ${config} broker_user
  config_get broker_pw ${config} broker_pw
  config_get id ${config} id
  config_get server_address ${config} server_address
  config_get device ${config} device
  config_get publish_delay ${config} publish_delay
  config_get debug ${config} debug

  procd_open_instance rtdnet_gateway
  procd_set_param command ${PROG} -h ${broker_host} -i ${id} --server-address ${server_address} --device ${device}
  [ "0${broker_user}" != "0" ] && procd_append_param command -u ${broker_user}
  [ "0${broker_pw}" != "0" ] && procd_append_param command -P ${broker_pw}
  [ "0${publish_delay}" -ne 0 ] && procd_append_param command --publish-delay ${publish_delay}
  [ "0${debug}" -eq 1 ] && procd_append_param command -d

  
  # respawn automatically if something died, be careful if you have an alternative process supervisor
  # if process dies sooner than respawn_threshold, it is considered crashed and after 5 retries the service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
  procd_set_param file /etc/config/rtdnet_gateway
  procd_set_param stdout 1 # forward stdout of the command to logd
  procd_set_param stderr 1 # same for stderr
  #procd_set_param user nobody # run service as user nobody
  procd_set_param pidfile /var/run/rtdnet_gateway.pid # write a pid file on instance start and remove it on stop
  procd_close_instance
}

start_service()
{
  config_load "${CFGNAME}"
  config_foreach rtdnet_gateway_instance rtdnet_gateway
}
